In [1]:
# Let's now import all the required libraries

import selenium
import pandas as pd
from selenium import webdriver

import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time

In [2]:
# let's first connect to the web driver
driver = webdriver.Chrome(r"C:\Users\Shrihan Manit\OneDrive\Desktop\chromedriver.exe")

Q4 : Scrape data of first 100 sunglasses listings on flipkart.com. You have to scrape four attributes:

Brand
Product Description
Price
To scrape the data you have to go through following steps:
Go to flipkart webpage by url https://www.flipkart.com/
Enter “sunglasses” in the search field where “search for products, brands and more” is written and click the search icon
after that you will reach to a webpage having a lot of sunglasses. From this page you can scrap the required data as usual.
after scraping data from the first page, go to the “Next” Button at the bottom of the page , then click on it

In [3]:
# Opening the flipkart on automated chrome browser
driver.get("https://www.flipkart.com/")

In [4]:
# Entering product in search bar as required
product = driver.find_element(By.CLASS_NAME,"_3704LK")
product.send_keys('Sunglasses')

time.sleep(3)
# Serching Item
search = driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search.click()

In [5]:
# Creating the empty list
Brand = []
Product_Description = []
Price = []
Discount = []
 
time.sleep(3)

#Scrapping the required details
start=0
end=3
for page in range(start,end):
    brand_tags=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')      
    for i in brand_tags:
        Brand.append(i.text)     
        
    Product_Desc_tags=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')     
    for i in Product_Desc_tags:
        Product_Description.append(i.text)    
        
    Price_tags=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]') 
    for i in Price_tags:
        Price.append(i.text)
        
    Discount_tags=driver.find_elements(By.XPATH,'//div[@class="_3Ay6Sb"]')
    for i in Discount_tags:
        Discount.append(i.text)
        
    nxt_button=driver.find_elements(By.XPATH,"//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href')) 
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [6]:
print(len(Brand),len(Product_Description),len(Price),len(Discount))

120 119 120 120

In [7]:
# Creating a dataframe from the above data
df = pd.DataFrame({'Brand':Brand[:100],'Product_Desc':Product_Description[:100],'Price':Price[:100],'Discount':Discount[:100]})
df

,Brand,Product_Desc,Price,Discount
0,ROZZETTA CRAFT,UV Protection Cat-eye Sunglasses (Free Size),₹359,82% off
1,VINCENT CHASE,"Polarized, UV Protection Round Sunglasses (51)","₹1,128",43% off
2,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),₹799,20% off
3,VINCENT CHASE,"by Lenskart Polarized, UV Protection Retro Squ...",₹901,54% off
4,ROZZETTA CRAFT,UV Protection Retro Square Sunglasses (Free Size),₹449,79% off
...,...,...,...,...
95,VINCENT CHASE,"UV Protection, Gradient Butterfly Sunglasses (62)",₹711,71% off
96,ROYAL SON,"UV Protection, Gradient Butterfly, Retro Squar...",₹559,72% off
97,AISLIN,"by Lenskart Polarized, UV Protection Round Sun...",₹443,70% off
98,VINCENT CHASE,"Gradient, UV Protection Aviator Sunglasses (57)",₹901,54% off
99,GANSTA,UV Protection Cat-eye Sunglasses (48),₹279,86% off

Q6: Scrape data for first 100 sneakers you find when you visit flipkart.com and search for “sneakers” in the search field. 
    You have to scrape 4 attributes of each sneaker:

Brand
Product Description
Price 
Discount
As shown in the below image, you have to scrape the tick marked attributes

In [8]:
# let's first connect to the web driver
driver = webdriver.Chrome(r"C:\Users\Shrihan Manit\OneDrive\Desktop\chromedriver.exe")

In [9]:
# Opening the flipkart on automated chrome browser
driver.get("https://www.flipkart.com/")

In [11]:
# Entering product in search bar as required
product = driver.find_element(By.CLASS_NAME,"_3704LK")
product.send_keys('Sneakers')

time.sleep(3)
# Serching Item
search = driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search.click()

In [12]:
# Creating the empty list
Brand = []
Product_Description = []
Price = []
Discount = []

In [13]:
time.sleep(3)

#Scrapping the required details
start=0
end=3
for page in range(start,end):
    brand_tags=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')      
    for i in brand_tags:
        Brand.append(i.text)     
        
    Product_Desc_tags=driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')     
    for i in Product_Desc_tags:
        Product_Description.append(i.text)    
        
    Price_tags=driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]') 
    for i in Price_tags:
        Price.append(i.text)
        
    Discount_tags=driver.find_elements(By.XPATH,'//div[@class="_3Ay6Sb"]')
    for i in Discount_tags:
        Discount.append(i.text)
        
    nxt_button=driver.find_elements(By.XPATH,"//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href')) 
    except:
        driver.get(nxt_button[0].get_attribute('href'))

In [14]:
print(len(Brand),len(Product_Description),len(Price),len(Discount))

120 110 120 120

In [15]:
# Creating a dataframe from the above data
df = pd.DataFrame({'Brand':Brand[:100],'Product_Desc':Product_Description[:100],'Price':Price[:100],'Discount':Discount[:100]})
df

,Brand,Product_Desc,Price,Discount
0,Labbin,Sneakers For Men,₹499,50% off
1,TR,Sneakers For Men,₹295,80% off
2,Shozie,"Breathable, Walking, Running, Casual, Gym Shoe...",₹379,62% off
3,BRUTON,Combo Pack Of 4 Casual Shoes Loafer Shoes Snea...,₹499,85% off
4,Layasa,supr Sneakers For Men,₹199,80% off
...,...,...,...,...
95,Blue Horse,Sneakers For Men,₹449,55% off
96,Sparx,Tigonis Casuals For Men Sneakers For Men (Whit...,₹619,27% off
97,Hida,"Stylish Comfortable Lightweight, Breathable Ca...",₹424,57% off
98,Vans on,Lightweight Combo Pack Of 3 Trendy Sneakers Sn...,"₹1,795",64% off
99,Rzisbo,STR2 Sneakers For Men,₹412,58% off

Q7: Go to the link - https://www.myntra.com/shoes Set second Price filter and Color filter to “Black”, as shown in the below image.

And then scrape First 100 shoes data you get. The data should include “Brand” of the shoes , Short Shoe description, price of the shoe as shown in the below image

In [16]:
# let's first connect to the web driver
driver = webdriver.Chrome(r"C:\Users\Shrihan Manit\OneDrive\Desktop\chromedriver.exe")

In [17]:
# Opening the Myntra website on automated chrome browser
driver.get("https://www.myntra.com/shoes")

In [18]:
time.sleep(4)

#clicking on price filter
pricebutton = driver.find_element(By.XPATH,"//ul[@class='price-list']/li[2]/label/div")
pricebutton.click()

#clicking on black colour 
blackbutton = driver.find_element(By.XPATH,'//li[@class="colour-listItem"]/label/div')
blackbutton.click()

In [19]:
# Creating the empty list
Brand = []
Product_Description = []
Price = []

#Scrapping the required details
start=0
end=2
for page in range(start,end):
    brand_tags=driver.find_elements(By.XPATH,"//div[@class='product-productMetaInfo']")      
    for i in brand_tags:
        Brand.append(i.text)     
        
    Product_Desc_tags=driver.find_elements(By.XPATH,"//div[@class='product-productMetaInfo']/h4[1]")     
    for i in Product_Desc_tags:
        Product_Description.append(i.text)    
        
    Price_tags=driver.find_elements(By.XPATH,'//div[@class="product-price"]') 
    for i in Price_tags:
        Price.append(i.text) 
        
        nxt_button=driver.find_elements(By.XPATH,'//a[@rel="next"]')

try:
    driver.get(nxt_button[1].get_attribute('href')) 
except:
    driver.get(nxt_button[0].get_attribute('href'))

In [20]:
print(len(Brand),len(Product_Description),len(Price))

100 100 100

In [21]:
# Creating a dataframe from the above data
df = pd.DataFrame({'Brand':Brand[:100],'Product_Desc':Product_Description[:100],'Price':Price[:100]})
df

,Brand,Product_Desc,Price
0,ADIDAS Originals\nMen Niteball II Sneakers\nRs...,Men Niteball II Sneakers,Rs. 9349Rs. 10999(15% OFF)
1,Red Tape\nMen Walking Shoes\nRs. 1619Rs. 5399(...,Men Walking Shoes,Rs. 1619Rs. 5399(70% OFF)
2,Puma\nSoftride Rift Breeze\nRs. 3249Rs. 6499(5...,Softride Rift Breeze,Rs. 3249Rs. 6499(50% OFF)
3,Red Tape\nMen Walking Shoes\nRs. 1589Rs. 5299(...,Men Walking Shoes,Rs. 1589Rs. 5299(70% OFF)
4,Nike\nMen DOWNSHIFTER11 Running Shoe\nRs. 3595...,Men DOWNSHIFTER11 Running Shoe,Rs. 3595Rs. 3995(10% OFF)
...,...,...,...
95,Carlton London\nWomen Solid Pumps\nRs. 1946Rs....,Women Solid Pumps,Rs. 1946Rs. 2995(35% OFF)
96,Nike\nKids Revolution 4 Running\nRs. 1299Rs. 3...,Kids Revolution 4 Running,Rs. 1299Rs. 3495(Rs. 2196 OFF)
97,Red Tape\nMen Walking Shoes\nRs. 1559Rs. 5199(...,Men Walking Shoes,Rs. 1559Rs. 5199(70% OFF)
98,HIGHLANDER\nMen Woven Design Sneakers\nRs. 658...,Men Woven Design Sneakers,Rs. 658Rs. 1198(45% OFF)
99,HRX by Hrithik Roshan\nMen Trainer-1 Gym Shoes...,Men Trainer-1 Gym Shoes,Rs. 1679Rs. 4799(65% OFF)

In [ ]:
Q5: Scrape 100 reviews data from flipkart.com for iphone11 phone. This task will be done in following steps:

First get the webpage https://www.flipkart.com/
Enter “iphone 11” in “Search” field .
Then click the search button
As shown in the above page you have to scrape the tick marked attributes.These are:

Rating
Review summary
Full review
You have to scrape this data for first 100 reviews

In [ ]:
# let's first connect to the web driver
driver = webdriver.Chrome(r"C:\Users\Shrihan Manit\OneDrive\Desktop\chromedriver.exe")

In [ ]:
# Opening the flipkart on automated chrome browser
driver.get("https://www.flipkart.com/")

In [ ]:
# Entering product in search bar as required
product = driver.find_element(By.CLASS_NAME,"_3704LK")
product.send_keys('iphone 11')

time.sleep(3)
# Serching Item
search = driver.find_element(By.CLASS_NAME,"L0Z3Pu")
search.click()

In [ ]:
search = driver.find_element(By.XPATH,'//div[@class="_4rR01T"]')
search.click()

In [ ]:
# Creating empty list
Rating = []
Review_summary = []
Full_review = []

start=0
end=10

# Scraping rating from given page
for page in range(start,end):
    rate = driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    for i in rate:
        Rating.append(i.text)
        
# Scraping review summary from given page
    review = driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    for i in review:
        Review_summary.append(i.text)

# Scraping full review from given page
    fullreview = driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]')
    for i in fullreview:
        Full_review.append(i.text)  
        
    nxt_button=driver.find_elements(By.XPATH,'//a[@class="_1LKTO3"]')
time.sleep(11)
try:
    driver.get(nxt_button[1].get_attribute('href')) 
except:
    driver.get(nxt_button[0].get_attribute('href'))

In [ ]:
print(len(Rating),len(Review_summary),len(Full_review))